attachment:
  _type: class
  metadata:
    _type: string
    _validation:
      length:
        max: 1000
  payload:
    _ref: template.*
    _type: ref
  type:
    _enum:
    - image
    - audio
    - video
    - file
    - template
    _type: enum
button:
  call:
    _doc: https://developers.facebook.com/docs/messenger-platform/send-api-reference/call-button
    _type: class
    payload: string
    title: string
    type:
      _type: string
      _value: phone_number
  postback:
    _doc: https://developers.facebook.com/docs/messenger-platform/send-api-reference/postback-button
    _type: class
    payload: string
    title: string
    type:
      _type: string
      _value: postback
  share:
    _doc: https://developers.facebook.com/docs/messenger-platform/send-api-reference/share-button
    _type: class
    payload: string
    title: string
    type:
      _type: string
      _value: element_share
  url:
    _type: class
    fallback_url: string
    messenger_extensions: boolean
    title: string
    type:
      _type: string
      _value: web_url
    url: string
    webview_height_ratio:
      _enum:
      - compact
      - tall
      - full
      _type: enum
element:
  generic:
    buttons: list
    default_action: string
    image_url: string
    item_url: string
    subtitle: string
    title: string
  list:
    buttons: list
    default_action: string
    image_url: string
    subtitle: string
    title: string
message:
  _type: class
  _validation: &id001
    message__or__sender_action:
      required: true
    sender_action:
      required: true
  generic_template:
    _type: class
    _validation: *id001
    message:
      attachment:
        _ref: generic.template
        _type: class
    notification_type: &id002
      _enum:
      - REGULAR
      - SILENT_PUSH
      - NO_PUSH
      _type: enum
    recipient: &id003
      _ref: recipient
      _type: class
    sender_action: &id004
      _enum:
      - typing_on
      - typing_off
      - mark_seen
      _type: enum
  list_template:
    _type: class
    _validation: *id001
    message:
      attachment:
        _ref: list.template
        _type: class
    notification_type: *id002
    recipient: *id003
    sender_action: *id004
  message:
    attachment:
      _type: object
    text: string
  notification_type: *id002
  quickreply:
    _type: class
    _validation: *id001
    message:
      quick_replies:
        _type: list
      text: string
    notification_type: *id002
    recipient: *id003
    sender_action: *id004
  recipient: *id003
  sender_action: *id004
quickreply:
  _type: class
  content_type:
    _enum:
    - text
    - location
    _type: enum
  image_url: string
  location:
    content_type:
      _type: string
      _value: location
  payload: string
  title: string
recipient:
  _validation:
    id__or__phone_numer:
      required: true
  id: string
  phone_number: string
template:
  button:
    _type: class
    buttons:
      _ref: button.*
      _type: list:ref
    template_type:
      _type: string
      _value: button
    text: string
  generic:
    payload:
      _type: class
      elements:
        _type: list
      template_type:
        _type: string
        _value: generic
    type:
      _type: string
      _value: template
  list:
    payload:
      _type: class
      elements:
        _type: list
      template_type:
        _type: string
        _value: list
    type:
      _type: string
      _value: template
